name: Run Docker Containers
on:
 push:
   branches:
     - main
#on:
 # schedule: 
  # - cron: "0 2 * * 1-6"    
  
jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Docker
        if: contains(github.event.head_commit.message, 'deploy')
        run: |
         docker login --username=ubteb --password=123456789
  
      - name: Build and push Docker image
        #if: contains(github.event.head_commit.message, 'deploy')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ubteb/barasa_cloud_computing:latest  
