name: Run Docker Containers
on:
 push:
   branches:
     - main
#on:
 # schedule: 
  # - cron: "0 2 * * 1-6"    
  
jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Docker
        run: |
         docker login --username=elijahmaiga --password=Boondocks@8541
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: elijahmaiga/barasa_cloud_computing:v5
          #trgfgffh
